[project]
name = "dbt-dlt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-duckdb>=1.7.0",
    "dlt[duckdb,workspace]>=0.3.0",
    "duckdb>=1.4.3",
    "python-dotenv>=1.0.0",
    "requests>=2.31.0",
]
